export const ACTUALIZAR = '  publicacion_actualizar '
export const CARGANDO = 'publicaciones_cargando '
export const ERROR = 'publicaciones_error '
export const COMERR = 'comentarios_error '
export const COMCARG = 'comentarios_cargando '
export const C_ACTUALIZAR = 'actualiza_comen'